# Generated by Django 5.1.3 on 2024-11-13 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Название задачи"),
                ),
                ("description", models.TextField(verbose_name="Описание задачи")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Новая", "Новая"),
                            ("Выполняется", "Выполняется"),
                            ("Завершена", "Завершена"),
                        ],
                        default="Новая",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("deadline", models.DateField(verbose_name="Дедлайн")),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата начала"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.user",
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
        ),
    ]
